export const PROGRAMAS = [
  "Administración Comercial y de Sistemas",
  "Administración de Empresas",
  "Administración de Empresas (Distancia)",
  "Bacteriología y Laboratorio Clínico",
  "Biología",
  "Comunicación Social",
  "Contaduría Pública",
  "Contaduría Pública (Distancia)",
  "Diseño Industrial",
  "Economía",
  "Economía (Distancia)",
  "Enfermería",
  "Filosofía",
  "Física",
  "Fisioterapia",
  "Fonoaudiología",
  "Ingeniería Ambiental",
  "Ingeniería Civil",
  "Ingeniería de Alimentos",
  "Ingeniería Eléctrica",
  "Ingeniería Electrónica",
  "Ingeniería en Telecomunicaciones",
  "Ingeniería Industrial",
  "Ingeniería Mecánica",
  "Ingeniería Mecatrónica",
  "Ingeniería Química",
  "Licenciatura en Ciencias Sociales",
  "Licenciatura en Educación Artística",
  "Licenciatura en Educación Física, Recreación y Deportes",
  "Licenciatura en Educación Física, Recreación y Deportes (Distancia)",
  "Licenciatura en Educación Infantil",
  "Licenciatura en Humanidades y Lengua Castellana",
  "Licenciatura en Lenguas Extranjeras Inglés Francés",
  "Matemática Aplicada",
  "Medicina",
  "Medicina Veterinaria",
  "Música",
  "Nutrición y Dietética",
  "Psicología",
  "Tecnología en Administración de Sistemas",
  "Tecnología en Alimentos",
  "Tecnología en Electricidad",
  "Tecnología en Electrónica",
  "Tecnología en Mecánica Industrial",
  "Tecnología en Saneamiento Ambiental",
  "Terapia Ocupacional",
  "Zootecnia",
].sort((a, b) => a.localeCompare(b, 'es'));
