export const PROGRAMAS = [
  "Administracion de Empresas",
  "Arquitectura",
  "Artes Visuales",
  "Bacteriologia y Laboratorio Clinico",
  "Biologia",
  "Comunicacion Social",
  "Contaduria Publica",
  "Derecho",
  "Diseno Industrial",
  "Economia",
  "Egresado",
  "Enfermeria",
  "Filosofia",
  "Fisica",
  "Fisioterapia",
  "Fonoaudiologia",
  "Geologia",
  "Ingenieria Agronomica",
  "Ingenieria Ambiental",
  "Ingenieria Civil",
  "Ingenieria de Alimentos",
  "Ingenieria de Sistemas",
  "Ingenieria Electrica",
  "Ingenieria Electronica",
  "Ingenieria en Telecomunicaciones",
  "Ingenieria Industrial",
  "Ingenieria Mecanica",
  "Ingenieria Mecatronica",
  "Ingenieria Quimica",
  "Licenciatura en Ciencias Sociales",
  "Licenciatura en Educacion Artistica",
  "Licenciatura en Educacion Fisica, Recreacion y Deportes",
  "Licenciatura en Educacion Infantil",
  "Licenciatura en Humanidades y Lengua Castellana",
  "Licenciatura en Lenguas Extranjeras Ingles-Frances",
  "Matematica Aplicada",
  "Medicina",
  "Medicina Veterinaria",
  "Microbiologia",
  "Musica",
  "Nutricion y Dietetica",
  "Otro",
  "Posgrado",
  "Psicologia",
  "Quimica",
  "Terapia Ocupacional",
  "Zootecnia",
].sort((a, b) => a.localeCompare(b, 'es'));
